name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to the latest version
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install --prefix techsaas-vision-frontend

      - name: Build frontend
        run: CI=false npm run build --prefix techsaas-vision-frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: techsaas-vision-frontend/build
