name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the entire repository from the root
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      # Step 3: Install dependencies for the frontend
      - name: Install frontend dependencies
        run: npm install --prefix techsaas-vision-frontend

      # Step 4: Build the frontend project
      - name: Build frontend
        run: npm run build --prefix techsaas-vision-frontend

      # Step 5: Deploy the frontend build to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: techsaas-vision-frontend/build  # Point to the frontend build directory
